// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	lecore: {
		/**
		 * L​e​c​o​r​e​ ​t​e​l​l​s​ ​y​o​u​ ​w​h​a​t​ ​L​e​e​t​c​o​d​e​ ​p​r​o​b​l​e​m​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​v​i​e​w​.
		 */
		desc: string
	}
	register: {
		/**
		 * E​m​a​i​l
		 */
		email: string
	}
	dashboard: {
		/**
		 * a​n​o​n​y​m​o​u​s
		 */
		anonymous: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logOut: string
	}
}

export type TranslationFunctions = {
	lecore: {
		/**
		 * Lecore tells you what Leetcode problem you need to review.
		 */
		desc: () => LocalizedString
	}
	register: {
		/**
		 * Email
		 */
		email: () => LocalizedString
	}
	dashboard: {
		/**
		 * anonymous
		 */
		anonymous: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Log out
		 */
		logOut: () => LocalizedString
	}
}

export type Formatters = {}
